In [1]:
pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in d:\users\ciberintegra_14\anaconda3\lib\site-packages (4.11.1)
Requirement already satisfied: soupsieve>1.2 in d:\users\ciberintegra_14\anaconda3\lib\site-packages (from beautifulsoup4) (2.3.1)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -cipy (d:\users\ciberintegra_14\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (d:\users\ciberintegra_14\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (d:\users\ciberintegra_14\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (d:\users\ciberintegra_14\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (d:\users\ciberintegra_14\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cipy (d:\users\ciberintegra_14\anaconda3\lib\site-packages)

In [3]:
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd

Cree varios datasets de distintas webs con webscraping, usando varios metodos.

La documentación de los distintos datasets se encuentran en el PDF adjunto en el repositorio.

# Frases (Beutiful Soup)

Primero hice un dataset de frases usando la web 'Quotes to Scrape' con sus autores y utilize el metodo de Beutiful Soup.

In [4]:
URL = "https://quotes.toscrape.com/"
page = requests.get(URL)

In [5]:
soup = BeautifulSoup(page.content, "html.parser")

In [6]:
quotes = soup.find_all("div", class_="quote")

Pedi la URL, carge el html y busque las cajas donde se encuentra la información.

In [7]:
df_data = {'Frase':[], 'Autor':[]}

In [8]:
for quote in quotes:
    frase = quote.find("span", itemprop="text")
    autor = quote.find("small", itemprop="author")
    df_data['Frase'].append(frase.text)
    df_data['Autor'].append(autor.text)
    print(frase.text)
    print(autor.text)
    print()

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
Albert Einstein

“It is our choices, Harry, that show what we truly are, far more than our abilities.”
J.K. Rowling

“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
Albert Einstein

“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
Jane Austen

“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”
Marilyn Monroe

“Try not to become a man of success. Rather become a man of value.”
Albert Einstein

“It is better to be hated for what you are than to be loved for what you are not.”
André Gide

“I have not failed. I've just found 10,000 ways that won't work.”
Thomas A. Edison

“A woman is like a tea bag; you never know how strong it is until it's in hot water.”
Eleanor Roosevelt

“A day without sunshine is like, you know, night.”
Steve Martin

Separé la frases y los autores del resto de la información y lo guardé en un diccionario.

In [9]:
df = pd.DataFrame(df_data)

In [10]:
df

                                               Frase              Autor
0  “The world as we have created it is a process ...    Albert Einstein
1  “It is our choices, Harry, that show what we t...       J.K. Rowling
2  “There are only two ways to live your life. On...    Albert Einstein
3  “The person, be it gentleman or lady, who has ...        Jane Austen
4  “Imperfection is beauty, madness is genius and...     Marilyn Monroe
5  “Try not to become a man of success. Rather be...    Albert Einstein
6  “It is better to be hated for what you are tha...         André Gide
7  “I have not failed. I've just found 10,000 way...   Thomas A. Edison
8  “A woman is like a tea bag; you never know how...  Eleanor Roosevelt
9  “A day without sunshine is like, you know, nig...       Steve Martin

Convertí el diccionario en un dataset.

# Frases (Selenium)

Esto es lo mismo, pero usando Selenium.

In [11]:
driver = webdriver.Chrome()
driver.get("https://quotes.toscrape.com/")
driver.title

'Quotes to Scrape'

Abrí el navegador Chrome y la página de Quotes.

In [12]:
df_data_2 = {'Frase':[], 'Autor':[]}

In [13]:
messages = driver.find_elements(By.CLASS_NAME, "text")
persons = driver.find_elements(By.CLASS_NAME, "author")

Busque el lugar donde encontre las frases y autores.

In [14]:
for message, person in zip(messages, persons):
    print("Frase:", message.text)
    print("Autor:", person.text)
    print()
    df_data_2['Frase'].append(message.text)
    df_data_2['Autor'].append(person.text)

Frase: “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
Autor: Albert Einstein

Frase: “It is our choices, Harry, that show what we truly are, far more than our abilities.”
Autor: J.K. Rowling

Frase: “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
Autor: Albert Einstein

Frase: “The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
Autor: Jane Austen

Frase: “Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”
Autor: Marilyn Monroe

Frase: “Try not to become a man of success. Rather become a man of value.”
Autor: Albert Einstein

Frase: “It is better to be hated for what you are than to be loved for what you are not.”
Autor: André Gide

Frase: “I have not failed. I've just found 10,000 ways that won't work.”
Autor: Thomas A. Edison

Frase: “A woman is like a tea bag; you never know how strong it is until it's in hot water.”
Autor: Eleanor Roosevelt

Frase: “A day without sunshine is like, you know, night.”
Autor: Steve Martin

In [15]:
df_2 = pd.DataFrame(df_data_2)

In [16]:
df_2

                                               Frase              Autor
0  “The world as we have created it is a process ...    Albert Einstein
1  “It is our choices, Harry, that show what we t...       J.K. Rowling
2  “There are only two ways to live your life. On...    Albert Einstein
3  “The person, be it gentleman or lady, who has ...        Jane Austen
4  “Imperfection is beauty, madness is genius and...     Marilyn Monroe
5  “Try not to become a man of success. Rather be...    Albert Einstein
6  “It is better to be hated for what you are tha...         André Gide
7  “I have not failed. I've just found 10,000 way...   Thomas A. Edison
8  “A woman is like a tea bag; you never know how...  Eleanor Roosevelt
9  “A day without sunshine is like, you know, nig...       Steve Martin

Al igual que el anterior lo guarde en un diccionario para posterioemente convertirlo en dataframe.

# BME (Beutiful Soup)

Aquí consulté la bolsa de mercado de Madrid, más especificamente el Mercado Continuo, que se esta en  constante cambio, por lo que es necesario a clarar que los datos que recogí vienen del día 13/02/2024.

In [17]:
URL2 = "https://www.bolsasymercados.es/bme-exchange/es/Mercados-y-Cotizaciones/Acciones/Mercado-Continuo/Precios/mercado-continuo"
page2 = requests.get(URL2)

In [18]:
soup2 = BeautifulSoup(page2.content, "html.parser")

In [19]:
col_df = []

In [20]:
columnas = soup2.find_all("div.table-responsive", style="")

In [21]:
for columna in columnas:
    col = columna.find("tr", colspan="1")
    print(col)
    print()

In [22]:
columnas

[]

Debido a que BME, es una web dinamica y Beutiful Soup no es tan efectiva con este tipo de webs. No pude sacar datos de esta página.

# BME (Selenium)

In [26]:
driver2 = webdriver.Chrome()
driver2.get(URL2)
driver2.title

'Mercado Continuo | BME Exchange'

In [68]:
col_sel = driver2.find_elements(By.XPATH, '//*[@id="root"]/div[3]/table/thead/tr/th')

In [70]:
columnas_df = []

In [71]:
for columna in col_sel:
    print(columna.text)
    columnas_df.append(columna.text)
    print()

Nombre

Último

% Dif.

Máximo

Mínimo

Volumen

Efectivo (miles €)

Fecha

Hora

Lo primero que hice, en parte para hacer pruebas y familiarizarme con la web, es separar las columnas y guardarlas en una lista para más tarde usarlas para el dataframe.

In [147]:
datos = driver2.find_elements(By.XPATH, '//*[@id="root"]/div[3]/table/tbody/tr/td')

In [166]:
filas = []

In [167]:
import re

for dato in datos:
    dato_text = dato.text.strip()  # Eliminar espacios en blanco alrededor del texto
    if dato_text.startswith('Suspendido'):
        fecha_match = re.search(r'\d{2}/\d{2}/\d{4}', dato_text)  # Buscar la fecha con una expresión regular
        if fecha_match:
            fecha_suspendido = fecha_match.group()
            filas.append('Suspendido')
            print('Suspendido')
            filas.append(fecha_suspendido)
            print(fecha_suspendido)
        else:
            filas.append(dato_text)# Si no se encuentra la fecha, agregar el texto completo
            print(dato.text)
    else:
        filas.append(dato_text)
        print(dato.text)
    print()

ACCIONA

110,5500

0,18%

110,6500

109,4000

15.003

1.651,18

14/02/2024

13:18:58

ACCIONA ENER

21,5000

0,00%

21,6800

21,3200

141.573

3.042,73

14/02/2024

13:16:34

ACERINOX

10,2500

-0,68%

10,2800

10,1750

150.698

1.540,87

14/02/2024

13:18:41

ACS

36,5900

0,55%

36,6400

36,2700

53.593

1.953,19

14/02/2024

13:15:25

ADOLFO DGUEZ

4,8000

3,45%

4,8000

4,7000

2.847

13,58

14/02/2024

12:30:01

AEDAS

18,8800

0,21%

19,1400

18,6600

6.625

124,46

14/02/2024

12:53:51

AENA

166,6500

0,12%

167,7500

165,4500

14.159

2.356,58

14/02/2024

13:12:19

AIRBUS SE

150,9400

1,37%

151,9800

148,7000

752

113,30

14/02/2024

13:06:29

AIRTIFICIAL

0,1420

-1,05%

0,1440

0,1420

439.455

62,83

14/02/2024

13:11:44

ALANTRA

8,8800

0,00%

9,0000

8,8800

3.319

29,74

14/02/2024

13:01:38

ALMIRALL

8,4900

0,41%

8,5100

8,4000

28.160

238,27

14/02/2024

13:18:30

AMADEUS

62,2400

0,35%

62,6200

62,0800

122.808

7.655,60

14/02/2024

13:18:30

AMPER

0,0815

-0,24%

0,0832

0,0805

322.213

26,30

14/02/2024

12:35:35

AMREST

6,2700

-0,32%

6,2700

6,2600

127

0,80

14/02/2024

12:41:37

APERAM

30,3600

-4,53%

30,3600

30,3000

389

11,79

14/02/2024

09:49:16

APPLUS

11,3700

-0,09%

11,3700

11,3700

1.004

11,42

14/02/2024

09:52:50

ARCELORMIT.

25,3900

0,18%

25,4250

25,0450

75.662

1.909,93

14/02/2024

13:17:52

ÁRIMA

6,5000

-

-

-

-

-

13/02/2024

Cierre

ATRESMEDIA

3,5580

-0,28%

3,5820

3,5560

39.794

141,77

14/02/2024

13:19:50

ATRYS HEALTH

3,0700

-0,97%

3,1300

3,0500

6.895

21,18

14/02/2024

12:35:32

AUDAX RENOV.

1,2800

-0,78%

1,2840

1,2780

5.362

6,86

14/02/2024

12:59:16

AUX.FERROCAR

32,1500

-1,38%

32,4500

32,1000

7.092

228,83

14/02/2024

13:18:51

AZKOYEN

5,9400

0,00%

6,1000

5,9400

2.766

16,58

14/02/2024

11:50:11

B.SANTANDER

3,7210

1,63%

3,7325

3,6810

9.292.878

34.518,07

14/02/2024

13:19:40

BA.SABADELL

1,1930

1,32%

1,1935

1,1510

7.925.592

9.364,99

14/02/2024

13:19:09

BANKINTER

5,8360

0,52%

5,8600

5,8040

753.376

4.395,12

14/02/2024

13:19:19

BAVIERA

23,6000

-1,67%

24,1000

23,4000

3.122

73,72

14/02/2024

12:42:11

BBVA

9,3300

0,60%

9,3600

9,2620

2.353.423

21.947,33

14/02/2024

13:19:47

BERKELEY

0,1856

1,20%

0,1858

0,1818

263.902

48,22

14/02/2024

13:17:39

BO.RIOJANAS

4,4400

0,45%

4,4400

4,4400

153

0,68

14/02/2024

12:37:40

BORGES BAIN

2,5400

0,79%

2,5400

2,5400

1

0,00

14/02/2024

12:00:07

CAIXABANK

4,0270

0,07%

4,0410

4,0040

4.198.373

16.915,96

14/02/2024

13:19:47

CAM

1,3400

-

-

-

-

-

Suspendido
09/12/2011

CASH

0,4625

-1,39%

0,4680

0,4615

91.573

42,59

14/02/2024

13:12:02

CCEP

62,3000

0,48%

62,3000

62,3000

47

2,93

14/02/2024

09:00:09

CELLNEX

33,2800

2,46%

33,4200

32,5000

229.055

7.572,80

14/02/2024

13:19:09

CEVASA

6,0000

0,00%

6,0000

6,0000

5.564

33,38

14/02/2024

12:00:07

CIE AUTOMOT.

24,5600

0,33%

24,6000

24,4000

6.464

158,70

14/02/2024

13:15:53

CLEOP

1,1500

-

-

-

-

-

Suspendido
12/06/2012

CORP. ALBA

48,5000

0,31%

48,5000

48,3500

230

11,14

14/02/2024

11:37:24

D.FELGUERA

0,6400

1,43%

0,6400

0,6300

90.843

57,86

14/02/2024

13:05:56

DEOLEO

0,2005

0,25%

0,2045

0,2000

181.441

36,33

14/02/2024

11:13:21

DESA

12,5000

-

-

-

-

-

13/02/2024

Cierre

DIA

0,0120

0,00%

0,0121

0,0120

2.348.033

28,23

14/02/2024

13:11:31

DOMINION

3,5300

-0,56%

3,5650

3,5250

30.803

108,93

14/02/2024

13:14:03

DURO FEL D24

0,0005

0,00%

0,0006

0,0002

18.629.000

6,02

14/02/2024

13:19:55

EBRO FOODS

14,9800

0,13%

15,0200

14,9400

6.383

95,62

14/02/2024

12:40:05

ECOENER

4,0300

-1,71%

4,1000

3,9600

1.644

6,62

14/02/2024

13:13:22

EDREAMS

6,9600

-1,28%

7,0600

6,9400

10.482

72,90

14/02/2024

12:58:06

ELECNOR

18,4000

0,27%

18,5000

18,3000

7.064

129,96

14/02/2024

13:19:48

Aquí busque los datos de la tabla, pero me encontre con que dos de las filas habian fucionado dos sus celdas por estar suspendidas, lo que termino dandome muchos problemas al momento organizar lo datos. Así tambien aproveche para separar

In [168]:
datos_df = []

In [169]:
for i in range(0, len(filas), 9):
    grupo = filas[i:i+9]
    datos_df.append(grupo)

In [170]:
datos_df

[['ACCIONA',
  '110,5500',
  '0,18%',
  '110,6500',
  '109,4000',
  '15.003',
  '1.651,18',
  '14/02/2024',
  '13:18:58'],
 ['ACCIONA ENER',
  '21,5000',
  '0,00%',
  '21,6800',
  '21,3200',
  '141.573',
  '3.042,73',
  '14/02/2024',
  '13:16:34'],
 ['ACERINOX',
  '10,2500',
  '-0,68%',
  '10,2800',
  '10,1750',
  '150.698',
  '1.540,87',
  '14/02/2024',
  '13:18:41'],
 ['ACS',
  '36,5900',
  '0,55%',
  '36,6400',
  '36,2700',
  '53.593',
  '1.953,19',
  '14/02/2024',
  '13:15:25'],
 ['ADOLFO DGUEZ',
  '4,8000',
  '3,45%',
  '4,8000',
  '4,7000',
  '2.847',
  '13,58',
  '14/02/2024',
  '12:30:01'],
 ['AEDAS',
  '18,8800',
  '0,21%',
  '19,1400',
  '18,6600',
  '6.625',
  '124,46',
  '14/02/2024',
  '12:53:51'],
 ['AENA',
  '166,6500',
  '0,12%',
  '167,7500',
  '165,4500',
  '14.159',
  '2.356,58',
  '14/02/2024',
  '13:12:19'],
 ['AIRBUS SE',
  '150,9400',
  '1,37%',
  '151,9800',
  '148,7000',
  '752',
  '113,30',
  '14/02/2024',
  '13:06:29'],
 ['AIRTIFICIAL',
  '0,1420',
  '-1,05%',
  '0,1440',
  '0,1420',
  '439.455',
  '62,83',
  '14/02/2024',
  '13:11:44'],
 ['ALANTRA',
  '8,8800',
  '0,00%',
  '9,0000',
  '8,8800',
  '3.319',
  '29,74',
  '14/02/2024',
  '13:01:38'],
 ['ALMIRALL',
  '8,4900',
  '0,41%',
  '8,5100',
  '8,4000',
  '28.160',
  '238,27',
  '14/02/2024',
  '13:18:30'],
 ['AMADEUS',
  '62,2400',
  '0,35%',
  '62,6200',
  '62,0800',
  '122.808',
  '7.655,60',
  '14/02/2024',
  '13:18:30'],
 ['AMPER',
  '0,0815',
  '-0,24%',
  '0,0832',
  '0,0805',
  '322.213',
  '26,30',
  '14/02/2024',
  '12:35:35'],
 ['AMREST',
  '6,2700',
  '-0,32%',
  '6,2700',
  '6,2600',
  '127',
  '0,80',
  '14/02/2024',
  '12:41:37'],
 ['APERAM',
  '30,3600',
  '-4,53%',
  '30,3600',
  '30,3000',
  '389',
  '11,79',
  '14/02/2024',
  '09:49:16'],
 ['APPLUS',
  '11,3700',
  '-0,09%',
  '11,3700',
  '11,3700',
  '1.004',
  '11,42',
  '14/02/2024',
  '09:52:50'],
 ['ARCELORMIT.',
  '25,3900',
  '0,18%',
  '25,4250',
  '25,0450',
  '75.662',
  '1.909,93',
  '14/02/2024',
  '13:17:52'],
 ['ÁRIMA', '6,5000', '-', '-', '-', '-', '-', '13/02/2024', 'Cierre'],
 ['ATRESMEDIA',
  '3,5580',
  '-0,28%',
  '3,5820',
  '3,5560',
  '39.794',
  '141,77',
  '14/02/2024',
  '13:19:50'],
 ['ATRYS HEALTH',
  '3,0700',
  '-0,97%',
  '3,1300',
  '3,0500',
  '6.895',
  '21,18',
  '14/02/2024',
  '12:35:32'],
 ['AUDAX RENOV.',
  '1,2800',
  '-0,78%',
  '1,2840',
  '1,2780',
  '5.362',
  '6,86',
  '14/02/2024',
  '12:59:16'],
 ['AUX.FERROCAR',
  '32,1500',
  '-1,38%',
  '32,4500',
  '32,1000',
  '7.092',
  '228,83',
  '14/02/2024',
  '13:18:51'],
 ['AZKOYEN',
  '5,9400',
  '0,00%',
  '6,1000',
  '5,9400',
  '2.766',
  '16,58',
  '14/02/2024',
  '11:50:11'],
 ['B.SANTANDER',
  '3,7210',
  '1,63%',
  '3,7325',
  '3,6810',
  '9.292.878',
  '34.518,07',
  '14/02/2024',
  '13:19:40'],
 ['BA.SABADELL',
  '1,1930',
  '1,32%',
  '1,1935',
  '1,1510',
  '7.925.592',
  '9.364,99',
  '14/02/2024',
  '13:19:09'],
 ['BANKINTER',
  '5,8360',
  '0,52%',
  '5,8600',
  '5,8040',
  '753.376',
  '4.395,12',
  '14/02/2024',
  '13:19:19'],
 ['BAVIERA',
  '23,6000',
  '-1,67%',
  '24,1000',
  '23,4000',
  '3.122',
  '73,72',
  '14/02/2024',
  '12:42:11'],
 ['BBVA',
  '9,3300',
  '0,60%',
  '9,3600',
  '9,2620',
  '2.353.423',
  '21.947,33',
  '14/02/2024',
  '13:19:47'],
 ['BERKELEY',
  '0,1856',
  '1,20%',
  '0,1858',
  '0,1818',
  '263.902',
  '48,22',
  '14/02/2024',
  '13:17:39'],
 ['BO.RIOJANAS',
  '4,4400',
  '0,45%',
  '4,4400',
  '4,4400',
  '153',
  '0,68',
  '14/02/2024',
  '12:37:40'],
 ['BORGES BAIN',
  '2,5400',
  '0,79%',
  '2,5400',
  '2,5400',
  '1',
  '0,00',
  '14/02/2024',
  '12:00:07'],
 ['CAIXABANK',
  '4,0270',
  '0,07%',
  '4,0410',
  '4,0040',
  '4.198.373',
  '16.915,96',
  '14/02/2024',
  '13:19:47'],
 ['CAM', '1,3400', '-', '-', '-', '-', '-', 'Suspendido', '09/12/2011'],
 ['CASH',
  '0,4625',
  '-1,39%',
  '0,4680',
  '0,4615',
  '91.573',
  '42,59',
  '14/02/2024',
  '13:12:02'],
 ['CCEP',
  '62,3000',
  '0,48%',
  '62,3000',
  '62,3000',
  '47',
  '2,93',
  '14/02/2024',
  '09:00:09'],
 ['CELLNEX',
  '33,2800',
  '2,46%',
  '33,4200',
  '32,5000',
  '229.055',
  '7.572,80',
  '14/02/2024',
  '13:19:09'],
 ['CEVASA',
  '6,0000',
  '0,00%',
  '6,0000',
  '6,0000',
  '5.564',
  '33,38',
  '14/02/2024',
  '12:00:07'],
 ['CIE AUTOMOT.',
  '24,5600',
  '0,33%',
  '24,6000',
  '24,4000',
  '6.464',
  '158,70',
  '14/02/2024',
  '13:15:53'],
 ['CLEOP', '1,1500', '-', '-', '-', '-', '-', 'Suspendido', '12/06/2012'],
 ['CORP. ALBA',
  '48,5000',
  '0,31%',
  '48,5000',
  '48,3500',
  '230',
  '11,14',
  '14/02/2024',
  '11:37:24'],
 ['D.FELGUERA',
  '0,6400',
  '1,43%',
  '0,6400',
  '0,6300',
  '90.843',
  '57,86',
  '14/02/2024',
  '13:05:56'],
 ['DEOLEO',
  '0,2005',
  '0,25%',
  '0,2045',
  '0,2000',
  '181.441',
  '36,33',
  '14/02/2024',
  '11:13:21'],
 ['DESA', '12,5000', '-', '-', '-', '-', '-', '13/02/2024', 'Cierre'],
 ['DIA',
  '0,0120',
  '0,00%',
  '0,0121',
  '0,0120',
  '2.348.033',
  '28,23',
  '14/02/2024',
  '13:11:31'],
 ['DOMINION',
  '3,5300',
  '-0,56%',
  '3,5650',
  '3,5250',
  '30.803',
  '108,93',
  '14/02/2024',
  '13:14:03'],
 ['DURO FEL D24',
  '0,0005',
  '0,00%',
  '0,0006',
  '0,0002',
  '18.629.000',
  '6,02',
  '14/02/2024',
  '13:19:55'],
 ['EBRO FOODS',
  '14,9800',
  '0,13%',
  '15,0200',
  '14,9400',
  '6.383',
  '95,62',
  '14/02/2024',
  '12:40:05'],
 ['ECOENER',
  '4,0300',
  '-1,71%',
  '4,1000',
  '3,9600',
  '1.644',
  '6,62',
  '14/02/2024',
  '13:13:22'],
 ['EDREAMS',
  '6,9600',
  '-1,28%',
  '7,0600',
  '6,9400',
  '10.482',
  '72,90',
  '14/02/2024',
  '12:58:06'],
 ['ELECNOR',
  '18,4000',
  '0,27%',
  '18,5000',
  '18,3000',
  '7.064',
  '129,96',
  '14/02/2024',
  '13:19:48']]

In [171]:
df_BME = pd.DataFrame(datos_df, columns = columnas_df)

In [172]:
df_BME

,Nombre,Último,% Dif.,Máximo,Mínimo,Volumen,Efectivo (miles €),Fecha,Hora
0,ACCIONA,"110,5500","0,18%","110,6500","109,4000",15.003,"1.651,18",14/02/2024,13:18:58
1,ACCIONA ENER,"21,5000","0,00%","21,6800","21,3200",141.573,"3.042,73",14/02/2024,13:16:34
2,ACERINOX,"10,2500","-0,68%","10,2800","10,1750",150.698,"1.540,87",14/02/2024,13:18:41
3,ACS,"36,5900","0,55%","36,6400","36,2700",53.593,"1.953,19",14/02/2024,13:15:25
4,ADOLFO DGUEZ,"4,8000","3,45%","4,8000","4,7000",2.847,"13,58",14/02/2024,12:30:01
5,AEDAS,"18,8800","0,21%","19,1400","18,6600",6.625,"124,46",14/02/2024,12:53:51
6,AENA,"166,6500","0,12%","167,7500","165,4500",14.159,"2.356,58",14/02/2024,13:12:19
7,AIRBUS SE,"150,9400","1,37%","151,9800","148,7000",752,"113,30",14/02/2024,13:06:29
8,AIRTIFICIAL,"0,1420","-1,05%","0,1440","0,1420",439.455,"62,83",14/02/2024,13:11:44
9,ALANTRA,"8,8800","0,00%","9,0000","8,8800",3.319,"29,74",14/02/2024,13:01:38
10,ALMIRALL,"8,4900","0,41%","8,5100","8,4000",28.160,"238,27",14/02/2024,13:18:30
11,AMADEUS,"62,2400","0,35%","62,6200","62,0800",122.808,"7.655,60",14/02/2024,13:18:30
12,AMPER,"0,0815","-0,24%","0,0832","0,0805",322.213,"26,30",14/02/2024,12:35:35
13,AMREST,"6,2700","-0,32%","6,2700","6,2600",127,"0,80",14/02/2024,12:41:37
14,APERAM,"30,3600","-4,53%","30,3600","30,3000",389,"11,79",14/02/2024,09:49:16
15,APPLUS,"11,3700","-0,09%","11,3700","11,3700",1.004,"11,42",14/02/2024,09:52:50
16,ARCELORMIT.,"25,3900","0,18%","25,4250","25,0450",75.662,"1.909,93",14/02/2024,13:17:52
17,ÁRIMA,"6,5000",-,-,-,-,-,13/02/2024,Cierre
18,ATRESMEDIA,"3,5580","-0,28%","3,5820","3,5560",39.794,"141,77",14/02/2024,13:19:50
19,ATRYS HEALTH,"3,0700","-0,97%","3,1300","3,0500",6.895,"21,18",14/02/2024,12:35:32
20,AUDAX RENOV.,"1,2800","-0,78%","1,2840","1,2780",5.362,"6,86",14/02/2024,12:59:16
21,AUX.FERROCAR,"32,1500","-1,38%","32,4500","32,1000",7.092,"228,83",14/02/2024,13:18:51
22,AZKOYEN,"5,9400","0,00%","6,1000","5,9400",2.766,"16,58",14/02/2024,11:50:11
23,B.SANTANDER,"3,7210","1,63%","3,7325","3,6810",9.292.878,"34.518,07",14/02/2024,13:19:40
24,BA.SABADELL,"1,1930","1,32%","1,1935","1,1510",7.925.592,"9.364,99",14/02/2024,13:19:09
25,BANKINTER,"5,8360","0,52%","5,8600","5,8040",753.376,"4.395,12",14/02/2024,13:19:19
26,BAVIERA,"23,6000","-1,67%","24,1000","23,4000",3.122,"73,72",14/02/2024,12:42:11
27,BBVA,"9,3300","0,60%","9,3600","9,2620",2.353.423,"21.947,33",14/02/2024,13:19:47
28,BERKELEY,"0,1856","1,20%","0,1858","0,1818",263.902,"48,22",14/02/2024,13:17:39
29,BO.RIOJANAS,"4,4400","0,45%","4,4400","4,4400",153,"0,68",14/02/2024,12:37:40
30,BORGES BAIN,"2,5400","0,79%","2,5400","2,5400",1,"0,00",14/02/2024,12:00:07
31,CAIXABANK,"4,0270","0,07%","4,0410","4,0040",4.198.373,"16.915,96",14/02/2024,13:19:47
32,CAM,"1,3400",-,-,-,-,-,Suspendido,09/12/2011
33,CASH,"0,4625","-1,39%","0,4680","0,4615",91.573,"42,59",14/02/2024,13:12:02
34,CCEP,"62,3000","0,48%","62,3000","62,3000",47,"2,93",14/02/2024,09:00:09
35,CELLNEX,"33,2800","2,46%","33,4200","32,5000",229.055,"7.572,80",14/02/2024,13:19:09
36,CEVASA,"6,0000","0,00%","6,0000","6,0000",5.564,"33,38",14/02/2024,12:00:07
37,CIE AUTOMOT.,"24,5600","0,33%","24,6000","24,4000",6.464,"158,70",14/02/2024,13:15:53
38,CLEOP,"1,1500",-,-,-,-,-,Suspendido,12/06/2012
39,CORP. ALBA,"48,5000","0,31%","48,5000","48,3500",230,"11,14",14/02/2024,11:37:24
40,D.FELGUERA,"0,6400","1,43%","0,6400","0,6300",90.843,"57,86",14/02/2024,13:05:56
41,DEOLEO,"0,2005","0,25%","0,2045","0,2000",181.441,"36,33",14/02/2024,11:13:21
42,DESA,"12,5000",-,-,-,-,-,13/02/2024,Cierre
43,DIA,"0,0120","0,00%","0,0121","0,0120",2.348.033,"28,23",14/02/2024,13:11:31
44,DOMINION,"3,5300","-0,56%","3,5650","3,5250",30.803,"108,93",14/02/2024,13:14:03
45,DURO FEL D24,"0,0005","0,00%","0,0006","0,0002",18.629.000,"6,02",14/02/2024,13:19:55
46,EBRO FOODS,"14,9800","0,13%","15,0200","14,9400",6.383,"95,62",14/02/2024,12:40:05
47,ECOENER,"4,0300","-1,71%","4,1000","3,9600",1.644,"6,62",14/02/2024,13:13:22
48,EDREAMS,"6,9600","-1,28%","7,0600","6,9400",10.482,"72,90",14/02/2024,12:58:06
49,ELECNOR,"18,4000","0,27%","18,5000","18,3000",7.064,"129,96",14/02/2024,13:19:48

Aquí tenemos nuestro dataset final de la bolsa de mercado de Madrid (Mercado Continuo)

Recuerden que la información de estos datasets, incluyendo los significados de las columnas, se encuentra adjunto en un PDF en el Github.